Fix failing test 2.3.1
Promise/A+ Tests for pinkySwear 2.3.1: If `promise` and `x` refer to the
same object, reject `promise` with a `TypeError' as the reason. via
return from a fulfilled promise:

Error: timeout of 2000ms exceeded